name: build-docs

on:
  push:
    branches:
      - main
      - main/docs

jobs:
  run-docfx:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: Kirbyrawr/docfx-action@master
        name: Docfx metadata
        with:
          args: metadata docs/docfx.json
      - uses: Kirbyrawr/docfx-action@master
        name: Docfx build
        with:
          args: build docs/docfx.json
          
  deploy:
    needs: run-docfx
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # with:
        #   submodules: true

      # Download the generated documentation
      - name: Download site artifact
        uses: actions/download-artifact@v1
        with:
          name: _site
          path: docs/_site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/_site